packages <- c("Hmisc") 
install.packages(packages, repos='http://cran.us.r-project.org')

source("http://bioconductor.org/biocLite.R")
biocLite("Biobase")
biocLite("DBI")
biocLite("RSQLite")
biocLite("AnnotationDbi")
biocLite("GO.db")
biocLite("RColorBrewer")
biocLite("latticeExtra")
biocLite("colorspace")
biocLite("munsell")
biocLite("scales")
biocLite("ggplot2")
biocLite("Hmisc")
biocLite("reshape")
biocLite("preprocessCore")
biocLite("WGCNA")
biocLite("illuminaHumanv3.db")
biocLite("illuminaHumanv4.db")
biocLite("animation")
biocLite("limma")
