#!/bin/bash
docker run -t -p 80:8787 -v /home/core/rstudio/:/home/rstudio/ -v /home/core/library/:/usr/local/lib/R/site-library/ -v /home/data/:/home/data/ -v /home/core/mixt/:/home/mixt/ --name rs rstudio
