#!/bin/bash
 docker run -v /home/core/kvik:/go/src/github.com/fjukstad/kvik -v /home/core/mixt/:/go/src/bitbucket.org/vdumeaux/mixt/ -p 8004:8004 -p 8787:8787 --name mixt --link=opencpu:opencpu -ti mixt /bin/bash
